import { Contact} from './contact';

export const CONTACTS: Contact[] = [
  { id: 1, name: 'Dr Grey', description: 'Meredith Grey, M.D., F.A.C.S. is a fictional character from the medical drama television series Grey\'s Anatomy, which airs on the American Broadcasting Company (ABC) in the United States. The character was created by series producer Shonda Rhimes, and is portrayed by actress Ellen Pompeo. Meredith is the series\' protagonist and title character, and was introduced as a surgical intern at the fictional Seattle Grace Hospital (later Seattle Grace-Mercy West Hospital, and afterwards Grey+Sloan Memorial), eventually obtaining the position of a surgical resident, and later the position of an attending, and in 2015, attaining the Chief of General Surgery position. As the daughter of world-renowned surgeon Ellis Grey, Meredith struggles with the everyday life of being in a competitive profession, maintaining the relationship with her one-night stand and eventual husband Derek Shepherd, her motherhood, and her friendships with her colleagues.'},
  { id: 2, name: 'Dr Karev', description: 'Alexander Michael Karev,[1] M.D. is a fictional character on the ABC television series Grey\'s Anatomy, portrayed by actor Justin Chambers.[2] Introduced as a surgical intern at the fictional Seattle Grace Hospital, Karev eventually obtained the position of resident, later becoming a pediatric surgical fellow. The relationships among colleagues Meredith Grey (Ellen Pompeo), Cristina Yang (Sandra Oh), Izzie Stevens (Katherine Heigl) and George O\'Malley (T. R. Knight) formed a focal point of the series.' },
  { id: 3, name: 'Dr Avery', description: 'Jackson Avery, M.D. is a fictional character in the ABC prime time medical drama, Grey\'s Anatomy, portrayed by actor Jesse Williams. The character was created by series creator and executive producer, Shonda Rhimes. He was introduced in season 6 episode "Invasion" as a surgical resident formerly from Mercy West Medical Center when it merges with Seattle Grace Hospital. Williams initially appeared as a recurring cast member,[2] and was later promoted to a series regular in season 7.[3] The character\'s main storyline involves Jackson trying to achieve success on his own instead of riding on the coattails of his surgeon grandfather\'s high reputation.' },
  { id: 4, name: 'Dr Wilson', description: 'Josephine Brooke Wilson M.D., formerly Josephine Alice Wilson and Josephine Brooke Wilson , and previously known as Brooke Stadler, is a fictional character from the medical drama television series Grey\'s Anatomy, which airs on the American Broadcasting Company (ABC) in the United States. The character was created by series producer Shonda Rhimes and is portrayed by actor Camilla Luddington. She was introduced in the ninth season premiere episode "Going, Going, Gone" as a surgical intern at Seattle Grace Mercy West Hospital, later renamed Grey Sloan Memorial in the same season. Luddington\'s character was conceptualized as the new love interest for Justin Chambers\' character, Alex Karev.' },
  { id: 5, name: 'Dr DeLuca', description: 'Andrew DeLuca, M.D. is a fictional character from the medical drama television series Grey\'s Anatomy, which airs on ABC in the United States. The character is portrayed by Giacomo Gianniotti. Andrew is introduced as a new surgical intern at Grey Sloan Memorial Hospital at the end of the eleventh season, eventually obtaining the position of a resident in the thirteenth season. He becomes one of the few interns and residents in later seasons to have personal connections to the attending surgeons. Andrew struggles with the everyday life of being in a competitive profession, fitting in with his peers, and navigating personal relationships with his friends and colleagues.' },
  { id: 6, name: 'Dr Pierce', description: 'I make terrible choices. I leave things behind and just let the bridges burn. I did it with Ethan. I did it with Dean. Oh, my God. I did it with my entire life. One day, I chose to learn a little bit about my birth mother. Cut to I live in her house with her daughter, and I work with the kind stranger who fathered me, and I left behind an entire life and family that no longer exists. My parents are divorced. My childhood home is sold. My mother is in Hawaii making soap now. I have no home. It\'s like I flew to this planet on an exploratory mission, and the earth blew up behind me and I can\'t go back. And now I\'m here with you aliens. Except I\'m the alien, and I\'m all alone, and I have nothing, and no one wants me.'},
  { id: 7, name: 'Dr Webber', description: 'Richard Webber, M.D. is a fictional character from the ABC medical drama television series Grey\'s Anatomy.[1] The character is portrayed by actor James Pickens Jr., and was created by Shonda Rhimes. He was previously the Chief of Surgery at Seattle Grace Mercy West Hospital for 12 years, and was replaced briefly by Derek Shepherd (Patrick Dempsey) and later Owen Hunt (Kevin McKidd).' },
  { id: 8, name: 'Dr Bailey', description: 'Miranda Bailey, M.D., F.A.C.S. is a fictional character from the medical drama television series Grey\'s Anatomy. The character was created by series creator and producer Shonda Rhimes, and has been portrayed by actress Chandra Wilson since the show\'s inception in 2005. Wilson has reprised her role in the spin-off series Private Practice and Station 19.' },
  { id: 9, name: 'Dr Hunt', description: 'Owen Hunt, M.D. is a fictional character from the medical drama television series Grey\'s Anatomy, which airs on the American Broadcasting Company (ABC) in the United States. The character was created by series\' producer Shonda Rhimes, and is portrayed by Scottish actor Kevin McKidd. He was introduced in season five as a U.S. Army trauma surgeon who served in war-torn Iraq, and subsequently joins the fictional Seattle Grace Hospital to teach medicine as a surgical attending, head of trauma surgery, and eventual chief of surgery, sometimes with unorthodox methods. Originally contracted to appear for a multi-episode story arc, he was upgraded to a series\' regular at the conclusion of his first appearance.' },
  { id: 10, name: 'Dr Shepherd', description: 'Amelia Frances Shepherd, M.D. is a fictional character on the ABC American television medical drama Private Practice, and the spinoff series\' progenitor show, Grey\'s Anatomy, portrayed by Caterina Scorsone. In her debut appearance in season three, Amelia visited her former sister-in-law, Addison Montgomery, and became a partner at the Oceanside Wellness Group. In July 2010, it was reported that she was promoted to series regular for the fourth season, after appearing in the final five episodes of season three. She remained in the series until the final episode.' },
];
